version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: a_strong_password
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: my_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
